apiVersion: example.org/v1alpha1
kind: AzureService
metadata:
  name: second-azure-service
spec:
  appName: "second"
  randomSuffix: "9411x"
  location: "westeurope"
  appServicePlanSize: "S1"
  imageName: "nginx"
  imageTag: "latest"
  imageRegistryUrl: "docker.io"
