# This composition is made of multiple resources including
# a Resource Group, App Service Plan, Web App, PostgreSQL Server, and Storage Account.
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azureservice-composition
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: CompositeAzureService
  resources:
  - name: resourcegroup
    base:
      # This is your updated base for the Resource Group
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
      metadata:
        name: default-rg
      spec:
        forProvider:
          location: italynorth
          tags:
            provisioner: crossplane
    patches:
      - fromFieldPath: "spec.appName"
        toFieldPath: "metadata.name"
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.location"

  - name: linuxserviceplan
    base:
      # This is your updated base for the App Service Plan
      apiVersion: web.azure.upbound.io/v1beta1
      kind: ServicePlan
      metadata:
        name: default-appserviceplan
        labels:
          testing.upbound.io/example-name: example
      spec:
        forProvider:
          location: italynorth
          resourceGroupName: default-rg
          skuName: "S1"
          osType: "Linux"
    patches:
      - fromFieldPath: "spec.appName"
        toFieldPath: "metadata.name"
        transforms:
          - type: string
            string:
              fmt: "%s-plan"
      - fromFieldPath: "spec.appServicePlanSize"
        toFieldPath: "spec.forProvider.skuName"
      - fromFieldPath: "spec.appName"
        toFieldPath: "spec.forProvider.resourceGroupName"
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.location"

  - name: linuxwebapp
    base:
      # This is your updated base for the App Service (a LinuxWebApp)
      apiVersion: web.azure.upbound.io/v1beta2
      kind: LinuxWebApp
      metadata:
        name: default-webapp
      spec:
        forProvider:
          resourceGroupName: default-rg
          name: default-webapp
          location: italynorth
          servicePlanIdRef:
            name: default-appserviceplan
          siteConfig:
            applicationStack:
              dockerImage: "nginx"
              dockerImageTag: "latest"
              dockerRegistryUrl: "docker.io"
    patches:
      - type: CombineFromComposite
        combine:
          strategy: string
          variables:
            - fromFieldPath: "spec.appName"
            - fromFieldPath: "spec.randomSuffix"
          string:
            fmt: "%s%s"
        toFieldPath: "metadata.name"
      - fromFieldPath: "spec.appName"
        toFieldPath: "spec.forProvider.resourceGroupName"
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: "spec.appName"
        toFieldPath: "spec.forProvider.servicePlanIdRef.name"
        transforms:
          - type: string
            string:
              fmt: "%s-plan"
      - fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.location"
      - fromFieldPath: "spec.imageName"
        toFieldPath: "spec.forProvider.siteConfig.applicationStack.dockerImage"
      - fromFieldPath: "spec.imageTag"
        toFieldPath: "spec.forProvider.siteConfig.applicationStack.dockerImageTag"
      - fromFieldPath: "spec.imageRegistryUrl"
        toFieldPath: "spec.forProvider.siteConfig.applicationStack.dockerRegistryUrl"

  - name: postgresql
    base:
      # This is your updated base for PostgreSQL Server
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta2
      kind: FlexibleServer
      metadata:
        name: default-db
      spec:
        forProvider:
          administratorLogin: exampleuser
          administratorPasswordSecretRef:
            key: example-key
            name: example-secret
            namespace: default
          autoGeneratePassword: true
          location: italynorth
          publicNetworkAccess: Enabled
          resourceGroupName: default-rg
          skuName: GP_Standard_D4s_v3
          storageMb: 32768
          storageTier: P30
          version: "16"
    patches:
      - type: CombineFromComposite
        combine:
          strategy: string
          variables:
            - fromFieldPath: "spec.appName"
            - fromFieldPath: "spec.randomSuffix"
          string:
            fmt: "%s%s"
        toFieldPath: "metadata.name"
      - fromFieldPath: "spec.appName"
        toFieldPath: "spec.forProvider.resourceGroupName"
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.location"

  - name: storageaccount
    base:
      # This is your updated base for the Storage Account (now an Account)
      apiVersion: storage.azure.upbound.io/v1beta2
      kind: Account
      metadata:
        name: default-storage
      spec:
        forProvider:
          accountKind: BlobStorage
          accountReplicationType: LRS
          accountTier: Standard
          location: italynorth
          resourceGroupName: default-rg
    patches:
      - type: CombineFromComposite
        combine:
          strategy: string
          variables:
            - fromFieldPath: "spec.appName"
            - fromFieldPath: "spec.randomSuffix"
          string:
            fmt: "%s%s"
        toFieldPath: "metadata.name"
      - fromFieldPath: "spec.appName"
        toFieldPath: "spec.forProvider.resourceGroupName"
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.location"
