apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: default-db
spec:
  forProvider:
    administratorLogin: adminuser
    location: eastus
    publicNetworkAccess: Enabled
    resourceGroupName: default-rg
    sku:
      capacity: 2
      family: Gen5
      tier: GeneralPurpose
    sslEnforcement: Enabled
    storageProfile:
      storageMB: 51200       # Minimum storage in MB; adjust as needed
      backupRetentionDays: 7 # Optional: number of days to retain backups
      geoRedundantBackup: Disabled
      storageAutogrow: Enabled
    version: "16"
  writeConnectionSecretToRef:
    name: default-db-conn
    namespace: crossplane-system
